### ISSUE TITLE
Upgrade to >= v1.5 to support K8s 1.22

### ISSUE THREAD

**Issue by megian** [projectsyn/component-cert-manager#48]
## Context
The current version of v1.4 still uses deprecated APIs unavailable in K8s 1.22. Please upgrade to  >= v1.5 to support K8s 1.22. "If you intend to upgrade to Kubernetes 1.22, you must upgrade to cert-manager 1.5." https://cert-manager.io/docs/release-notes/release-notes-1.5/#api-deprecation 

## Alternatives
N/A

**Comment by ccremer** [comment]
I think this would need to be labelled a breaking change for the component, right?
Because basically there's a major transient dependency update within that change. Or put in other words: One cannot just merge a PR if it would have been created by Renovate, one needs to do manual action before.

**Comment by glrf** [comment]
No, as far as I understood: k8s 1.22 requires cert-manager 1.5, but cert-manager 1.5 runs fine on k8s 1.21. So upgrade to 1.5 is only a minor update to `v2.4.0`.

Upgrading to cert-manager 1.6 is arguable a breaking change, as [it deprecates old cert-manager resources](https://cert-manager.io/docs/release-notes/release-notes-1.6/). This will probably be fine, but there could be issues for [cluster that ran cert-manager < 1.0](https://cert-manager.io/docs/installation/upgrading/upgrading-1.5-1.6/) 

So I would propose for now that we update to cert-manager 1.5 to fix this issue and postpone the update to 1.6

**Comment by megian** [comment]
> So I would propose for now that we update to cert-manager 1.5 to fix this issue and postpone the update to 1.6

Fine with that. We just need a solution for OpenShift 4.9 currently.

**Comment by tobru** [comment]
> but there could be issues for cluster that ran cert-manager < 1.0

I'm not sure if we have that condition. So I'm in favor of going to 1.6 ... We would of course need to mention that in the release notes of the component.

**Comment by glrf** [comment]
> > but there could be issues for cluster that ran cert-manager < 1.0
> 
> I'm not sure if we have that condition. So I'm in favor of going to 1.6 ... We would of course need to mention that in the release notes of the component.

I would expect we do, because we only updated this component to use cert-manager >= 1.0  in July with https://github.com/projectsyn/component-cert-manager/pull/16

**Comment by megian** [comment]
> I'm not sure if we have that condition.

We have no overview over that currently. It will require to check all the deployments on all clusters to verify we don't have it. So v1.5 would give us more time.

**Comment by ccremer** [comment]
We definitely had clusters running < 1.0, I touched some of those.
But I can't remember which ones...
